# Generated by Django 5.1.3 on 2024-12-25 08:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='address',
            field=models.TextField(null=True),
        ),
        migrations.CreateModel(
            name='LeadStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_status', models.CharField(choices=[('NEW', 'New Lead'), ('CONTACTED', 'Contacted'), ('MEETING_SCHEDULED', 'Meeting Scheduled'), ('NEGOTIATING', 'Negotiating'), ('CONVERTED', 'Converted'), ('LOST', 'Lost')], max_length=20)),
                ('new_status', models.CharField(choices=[('NEW', 'New Lead'), ('CONTACTED', 'Contacted'), ('MEETING_SCHEDULED', 'Meeting Scheduled'), ('NEGOTIATING', 'Negotiating'), ('CONVERTED', 'Converted'), ('LOST', 'Lost')], max_length=20)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='leads.restaurant')),
            ],
        ),
    ]
