# Generated by Django 5.1.3 on 2024-12-26 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interaction_tracking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interaction',
            name='interaction_type',
            field=models.CharField(choices=[('CALL', 'Call'), ('EMAIL', 'Email')], max_length=50),
        ),
    ]
