# Generated by Django 5.1.3 on 2024-12-28 06:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interaction_tracking', '0002_alter_interaction_interaction_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='interaction',
            name='order_placed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='interaction',
            name='interaction_type',
            field=models.CharField(choices=[('CALL', 'Call'), ('EMAIL', 'Email'), ('ORDER', 'Order')], max_length=50),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_details', models.TextField()),
                ('quantity', models.IntegerField()),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('order_date', models.DateTimeField(auto_now_add=True)),
                ('interaction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='order', to='interaction_tracking.interaction')),
            ],
        ),
    ]
