# Generated by Django 5.1.3 on 2025-01-02 14:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interaction_tracking', '0003_interaction_order_placed_and_more'),
        ('leads', '0003_restaurant_cuisine_type_restaurant_restaurant_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='total_price',
            new_name='amount',
        ),
        migrations.RemoveField(
            model_name='order',
            name='interaction',
        ),
        migrations.RemoveField(
            model_name='order',
            name='product_details',
        ),
        migrations.RemoveField(
            model_name='order',
            name='quantity',
        ),
        migrations.AddField(
            model_name='order',
            name='lead',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='leads.restaurant'),
        ),
    ]
