# Generated by Django 5.1.3 on 2025-01-02 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interaction_tracking', '0004_rename_total_price_order_amount_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='lead',
            new_name='restaurant',
        ),
    ]
