# Generated by Django 5.1.3 on 2025-01-02 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('performance_tracking', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
