# Generated by Django 5.1.3 on 2024-12-26 12:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('leads', '0003_restaurant_cuisine_type_restaurant_restaurant_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='CallPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('call_frequency_days', models.IntegerField(default=7)),
                ('last_call_date', models.DateTimeField(blank=True, null=True)),
                ('restaurant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='call_plan', to='leads.restaurant')),
            ],
        ),
    ]
