# Generated by Django 5.1.3 on 2024-12-28 07:38

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('call_planning', '0001_initial'),
        ('leads', '0003_restaurant_cuisine_type_restaurant_restaurant_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='callplan',
            old_name='last_call_date',
            new_name='last_called',
        ),
        migrations.RemoveField(
            model_name='callplan',
            name='call_frequency_days',
        ),
        migrations.RemoveField(
            model_name='callplan',
            name='restaurant',
        ),
        migrations.AddField(
            model_name='callplan',
            name='frequency',
            field=models.CharField(choices=[('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('BIWEEKLY', 'Bi-Weekly'), ('MONTHLY', 'Monthly')], default='DAILY', max_length=20),
        ),
        migrations.AddField(
            model_name='callplan',
            name='lead',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='leads.restaurant'),
        ),
        migrations.AddField(
            model_name='callplan',
            name='next_call_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 28, 7, 37, 51, 458319, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AddField(
            model_name='callplan',
            name='notes',
            field=models.TextField(blank=True),
        ),
    ]
