# Generated by Django 5.1.3 on 2024-12-28 07:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('call_planning', '0002_rename_last_call_date_callplan_last_called_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callplan',
            name='next_call_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
